/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import entidades.Alumno;
import java.util.ArrayList;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author agusv
 */
public class MostrarAlumnos extends javax.swing.JInternalFrame {
    ArrayList<Alumno> alumnoList = new ArrayList<>();
    DefaultTableModel tableModel = new DefaultTableModel();

    /**
     * Creates new form MostrarAlumnos
     */
    public MostrarAlumnos(ArrayList<Alumno> alumnoList) {
        initComponents();
        this.alumnoList = alumnoList;
        mostrarTabla();
    }
    
     public void mostrarTabla() {
        DefaultTableModel tableModel = (DefaultTableModel) jtableAlumnos.getModel();        
        
        for (Alumno alumnoAux : alumnoList) {            
            tableModel
                    .insertRow(alumnoList.indexOf(alumnoAux),new Object[] {
                            alumnoAux.getIdAlumno(),
                            alumnoAux.getNombre(),
                            alumnoAux.getApellido(),
                            alumnoAux.getFechNac().toString(),
                            alumnoAux.getDni() });
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtableAlumnos = new javax.swing.JTable();

        setClosable(true);

        jtableAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Apellido", "Fecha Nacimiento", "DNI"
            }
        ));
        jScrollPane1.setViewportView(jtableAlumnos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtableAlumnos;
    // End of variables declaration//GEN-END:variables
}
